project_id = "gbpqlzjtcuhijtouwrvn"

[functions.send-test-results]
verify_jwt = false

[functions.verify-teacher-credentials]
verify_jwt = false

[functions.list-results]
verify_jwt = false

[functions.replay-signed-url]
verify_jwt = false

[functions.update-replay-url]
verify_jwt = false

[functions.seed-teacher]
verify_jwt = false

[functions.claim-admin]
verify_jwt = true

[functions.generate-test]
verify_jwt = false

[functions.publish-test]
verify_jwt = false

[functions.delete-test]
verify_jwt = false

[functions.grade-quiz-submission]
verify_jwt = false

[functions.create-session]
verify_jwt = false

[functions.start-session]
verify_jwt = false

[functions.stop-session]
verify_jwt = false

[functions.join-session]
verify_jwt = false

[functions.page-beacon]
verify_jwt = false
